#!/bin/sh

echo "Starting rcS..."

echo "++ Mounting filesystem"
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp

echo "++ Setting up mdev"

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

mkdir -p /dev/pts
mkdir -p /dev/i2c
mount -t devpts devpts /dev/pts
echo "++ set hostname= zedboard"
busybox hostname zedboard
echo "++ Starting telnet daemon"
telnetd -l /bin/sh

#echo "++ Starting http daemon"
#httpd -h /var/www

echo "++ Starting ftp daemon"
tcpsvd 0:21 ftpd ftpd -w /&

echo "++ Starting dropbear (ssh) daemon"
dropbear

echo "++ insmod smartcar.ko"
insmod /root/mydriver.ko

echo "++ ifconfig eth0 up"
ifconfig eth0 192.168.1.100 

sleep 5
/root/DemoScripts/webcam.sh

ehco "++ Starting smartcar(tcp) daemon"
/root/smart_car/zynq_server_arm.o
echo "rcS Complete"
